const User = require("../models/User");

const importUsers = async () => {
  const users = [];
  for (let i = 0; i < 20; i++) {
    const newUser = {
      username: `${generateRandomUsername()}${i}`,
      email: `email${i}@test.com`,
      password: "password",
      firstName: `firstName${i}`,
      lastName: `lastName${i}`,
      address: `address${i}`,
    };
    users.push(newUser);
  }
  await User.insertMany(users);
};

function generateRandomUsername() {
  const randAdj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randNoun = nouns[Math.floor(Math.random() * nouns.length)];
  return `${randAdj}${randNoun}`;
}

const adjectives = [
  "Angelic",
  "Blissful",
  "Breezy",
  "Buoyant",
  "Celestial",
  "Cosmic",
  "Cozy",
  "Dashing",
  "Dazzling",
  "Dynamic",
  "Echoing",
  "Enchanting",
  "Energetic",
  "Ethereal",
  "Frosted",
  "Gleaming",
  "Glistening",
  "Glorious",
  "Glowing",
  "Harmonious",
  "Infinite",
  "Jovial",
  "Jubilant",
  "Lively",
  "Majestic",
  "Mesmerizing",
  "Mystical",
  "Playful",
  "Pristine",
  "Pulsating",
  "Radiant",
  "Resplendent",
  "Rhythmic",
  "Scented",
  "Serene",
  "Sizzling",
  "Soothing",
  "Sparkling",
  "Spirited",
  "Splendid",
  "Swift",
  "Timeless",
  "Tranquil",
  "Velvet",
  "Vibrant",
  "Vivid",
  "Whimsical",
  "Whispering",
  "Wondrous",
  "Zesty",
];

const nouns = [
  "Aurora",
  "Cascade",
  "Cascade",
  "Cascade",
  "Celestial",
  "Celestial",
  "Dream",
  "Echo",
  "Elysium",
  "Elysium",
  "Enigma",
  "Enigma",
  "Ethereal",
  "Harmony",
  "Harmony",
  "Haven",
  "Horizon",
  "Horizon",
  "Lagoon",
  "Lagoon",
  "Lullaby",
  "Lullaby",
  "Meadow",
  "Mirage",
  "Mosaic",
  "Mosaic",
  "Nimbus",
  "Nimbus",
  "Oasis",
  "Oasis",
  "Odyssey",
  "Odyssey",
  "Radiance",
  "Radiance",
  "Serendipity",
  "Serenity",
  "Solitude",
  "Solitude",
  "Starlight",
  "Symphony",
  "Tranquility",
  "Utopia",
  "Utopia",
  "Velvet",
  "Whisper",
  "Whisper",
  "Zenith",
  "Zenith",
  "Zephyr",
  "Zephyr",
];

module.exports = importUsers;
