const registerLists = {
  inputValues: [
    { proper: "Username", lowercase: "username" },
    { proper: "Email", lowercase: "email" },
    { proper: "Password", lowercase: "password" },
    { proper: "First Name", lowercase: "firstName" },
    { proper: "Last Name", lowercase: "lastName" },
    { proper: "Billing Address", lowercase: "billingAddress" },
    { proper: "Shipping Address", lowercase: "shippingAddress" },
  ],
  firstNames: [
    "James",
    "Jessica",
    "John",
    "Jennifer",
    "Jack",
    "Julia",
    "Jonathan",
    "Jasmine",
    "Joseph",
    "Jocelyn",
    "Jackson",
    "Jenna",
    "Jake",
    "Jade",
    "Jordan",
  ],
  lastNames: [
    "Smith",
    "Stewart",
    "Sanders",
    "Sullivan",
    "Simpson",
    "Stevens",
    "Snyder",
    "Shaw",
    "Schmidt",
    "Sharp",
    "Singleton",
    "Silva",
    "Saunders",
    "Stephens",
    "Scott",
  ],
  addresses: [
    "123 Main St, Monroe, WI 53566",
    "456 Oak St, Springfield, IL 62701",
    "789 Elm St, Portland, OR 97201",
    "101 Pine St, Austin, TX 78701",
    "202 Cedar St, Denver, CO 80202",
    "303 Maple St, Seattle, WA 98101",
    "404 Birch St, Phoenix, AZ 85001",
    "505 Spruce St, Nashville, TN 37201",
    "606 Redwood St, Boston, MA 02101",
    "707 Walnut St, Atlanta, GA 30301",
    "808 Cypress St, Chicago, IL 60601",
    "909 Magnolia St, San Francisco, CA 94101",
    "111 Oakwood St, Miami, FL 33101",
    "222 Pinecrest St, New York, NY 10001",
    "333 Birchwood St, Los Angeles, CA 90001",
  ],
};

export default registerLists;
